### ISSUE TITLE
File not found: https://dl.linto.ai/downloads/model-distribution/decoding-graphs/LVCSR/fr-FR/decoding_graph_fr-FR_Small_v1.0.0.zip

### ISSUE THREAD

**Issue by zsellami** [linto-ai/linto-platform-stt-standalone-worker#5]
On https://github.com/linto-ai/linto-platform-stt-standalone-worker the small decoding graph file is not found when tried to download it.

**Comment by irebai** [comment]
The Readme is now updated.
Thank you!
