### ISSUE TITLE
Streaming instead of file POST

### ISSUE THREAD

**Issue by wibimaster** [linto-ai/linto-platform-stt-standalone-worker#6]
Hi !

Is a streaming feature (to get live output) on the roadmap ?

You're using Kaldi, maybe with GStreamer ?

Thanks !

**Comment by irebai** [comment]
Hello
The streaming is already available (https://github.com/linto-ai/linto-platform-stt-standalone-worker-streaming)
We use VOSK-api instead of GStreamer
