### ISSUE TITLE
docker run failed

### ISSUE THREAD

**Issue by eheintzmann** [linto-ai/linto-platform-stt-standalone-worker#7]
Hello,
I get an error when running pre-built image from docker hub :

```bash
docker pull lintoai/linto-platform-stt-standalone-worker:latest
...
docker run lintoai/linto-platform-stt-standalone-worker:latest
...
Status: Downloaded newer image for lintoai/linto-platform-stt-standalone-worker:latest
INFO:__stt-standelone-worker__:Create the new config files
INFO:__stt-standelone-worker__:Load acoustic model and decoding graph
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:462) Cannot open config file: /opt/models/AM/conf/online.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
```

I also tried "latest-unstable" and "3.1.1" tags without success.

**Comment by irebai** [comment]
Hello,
You can't run the image like you did. In fact, you need to clone this repository, download the linSTT models, configure the environment file (.envdefault => .env), and then start the service using the docker-compose or docker run (using the requested parameters as defined in docker-compose.yml)
Please read the Readme for more details about how to run the service.
