### ISSUE TITLE
LinTO Doc

### ISSUE THREAD

**Issue by damienlaine** [linto-ai/linto-platform-stt-standalone-worker#9]
https://doc.linto.ai/#/ 

 Description

**Comment by damienlaine** [comment]
Hello @tagny i assigned @irebai and moved the issue in the correct project.

**Comment by irebai** [comment]
Hi @tagny,
did you run the curl command in the test folder since this command use the file "@bonjour.wav" that is in this folder ?
could you, after executing this command, print the worker service logs to see what is going on exactly please.

**Comment by tagny** [comment]
> Hi @tagny,
> did you run the curl command in the test folder since this command use the file "@bonjour.wav" that is in this folder ?
> could you, after executing this command, print the worker service logs to see what is going on exactly please.

Hi @irebai 
Yes I did run the the exact curl command that is in the **test_deployment.sh**  script from the **test** folder of this repository that contains the file "bonjour.wav".  Nothing more is added to this log as if the request never reached the service:  
```
INFO:__stt-standelone-worker__:Create the new config files
INFO:__stt-standelone-worker__:Create word_boundary.int based on phones.txt
INFO:__stt-standelone-worker__:Load acoustic model and decoding graph
LOG (VoskAPI:Configure():vosk/model.cc:134) Loading decode config file from /opt/config/online.conf
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:159) Am model file /opt/models/AM/.//final.mdl
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.022691 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:176) Loading HCLG from /opt/models/LM/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:196) Loading words from /opt/models/LM/words.txt
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:205) Loading winfo /opt/models/LM/word_boundary.int
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:260) Ivector silence weighting is deactivated
```

**Comment by irebai** [comment]
Hi @tagny,
In fact, you lunched the worker service with ports 8888:8888. However, the worker is running on port 80 (target port in docker-compose.yml and the default value in tools.py).
So, you need either changer the port when you run the docker (8888:80) or specify the worker's port to run on (-e SERVICE_PORT=8888).
I recommend you to use `docker-compse up` to run the service and `.env` file to specify the worker paramerters.

**Comment by tagny** [comment]
Great! It works just fine after :

- downloading and unzipping the language models:
  - https://dl.linto.ai/downloads/model-distribution/acoustic-models/fr-FR/linSTT_AM_fr-FR_v1.0.0.zip
  - https://dl.linto.ai/downloads/model-distribution/decoding-graphs/LVCSR/fr-FR/decoding_graph_fr-FR_Small_v1.1.0.zip
- downloading the swagger image: `docker pull swaggerapi/swagger-ui`
- cloning this repository : `git clone  https://github.com/linto-ai/linto-platform-stt-standalone-worker`
- `cd linto-platform-stt-standalone-worker`
- assigning the absolute paths of the language model folders and of the swagger .yml file  to the environment variables in the file `.env`
- running the source code using `cd linto-platform-stt-standalone-worker; docker-compose up` after a
Even swagger works well at http://localhost:8888/api-doc.
Than you very much @irebai. I will check the bigger language model for French and English (https://dl.linto.ai/downloads/model-distribution/acoustic-models/, ttps://dl.linto.ai/downloads/model-distribution/decoding-graphs/LVCSR), and the streaming STT standalone worker next.

**Comment by irebai** [comment]
It's great to hear that !
Enjoy using our models and services :)
For any questions or recommendations, please contact me at: irebai@linagora.com (or rebai_ilyes@hotmail.fr)
